name: Scrape Stock Prices
on:
  schedule:
    - cron: "0 0 * * *"
  
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        with
        python-version:"3.x"
        
    - name: Install dependencies
      run:
        python -m pip install --upgrade pop
        pip install -r requirements. txt
        
    - name: Scrape Stock Prices
      run: python scrape_stock_prices.py
